/**
 * sandbox-escape.test.mjs — macOS Seatbelt escape vector tests.
 *
 * These tests verify that the boxsh macOS sandbox profile is hardened against
 * known escape vectors.  Each test targets a specific weakness identified in
 * the analysis of the SBPL profile generated by build_sbpl().
 *
 * The tests are organized in phases:
 *   Phase 1 — Mach IPC restrictions
 *   Phase 2 — Process / signal restrictions
 *   Phase 3 — sysctl restrictions
 *   Phase 4 — IPC restrictions
 *   Phase 5 — sandbox_init failure handling
 *   Phase 6 — file-ioctl restrictions
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { BOXSH, TEMPDIR } from './helpers.mjs';

// Skip the entire file on non-macOS platforms.
const IS_MACOS = process.platform === 'darwin';

// Helper: run boxsh --try with a given CWD and -c command.
function tryRun(cwd, cmd, timeout_ms = 8000) {
  return spawnSync(BOXSH, ['--try', '-c', cmd], {
    encoding: 'utf8',
    cwd,
    timeout: timeout_ms,
  });
}

// ============================================================================
// Phase 1 — Mach IPC restrictions
//
// (allow mach*) grants the sandboxed process access to ALL XPC services.
// A malicious process can ask a privileged unsandboxed service to perform
// file I/O on its behalf, escaping filesystem restrictions.
// ============================================================================

describe('Phase 1 — Mach IPC restrictions', { skip: !IS_MACOS }, () => {

  test('lsappinfo (launchservicesd XPC) should be denied', () => {
    // lsappinfo talks to com.apple.coreservices.launchservicesd.
    // With (allow mach*), this enumerates all running apps — information leak.
    // After hardening to a whitelist, the XPC lookup should be denied.
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-mach-'));
    try {
      const r = tryRun(cwd, 'lsappinfo list 2>&1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      // After fix: lsappinfo should fail because launchservicesd is NOT in whitelist
      // (or produces empty/error output).
      const output = r.stdout;
      assert.ok(
        !output.includes('bundleID='),
        `ESCAPE: lsappinfo can enumerate running apps via unrestricted Mach IPC.\n` +
        `  This means (allow mach*) is still active — should be replaced with a whitelist.\n` +
        `  Got: ${output.slice(0, 200)}`
      );
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });

  test('notifyutil uses whitelisted notification_center (safe)', () => {
    // notifyutil uses com.apple.system.notification_center — this service is
    // safe (pub/sub notifications only, no file proxy capability) and is in
    // the whitelist.  This test ensures it keeps working.
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-mach-'));
    try {
      const r = tryRun(cwd, 'notifyutil -g com.apple.system.timezone 2>&1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      assert.ok(r.stdout.includes('EXIT:0'),
        `notifyutil should work via whitelisted notification_center service`);
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });
});

// ============================================================================
// Phase 2 — Process / signal restrictions
//
// (allow process*) grants full process enumeration of ALL processes.
// (allow signal) allows sending signals to ANY process, not just same-sandbox.
// ============================================================================

describe('Phase 2 — Process / signal restrictions', { skip: !IS_MACOS }, () => {

  test('should not be able to send signals to host PID 1', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-sig-'));
    try {
      // kill -0 checks if process is reachable. PID 1 (launchd) should be
      // unreachable from sandbox with (target same-sandbox).
      const r = tryRun(cwd, 'kill -0 1 2>&1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      assert.ok(
        r.stdout.includes('EXIT:1') || r.stdout.includes('not permitted'),
        `Expected signal to PID 1 to be denied, got: ${r.stdout}`
      );
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });
});

// ============================================================================
// Phase 3 — sysctl restrictions
//
// (allow sysctl*) grants BOTH read AND write access to ALL sysctl variables.
// With the current profile, 1700+ sysctl entries are readable.
// After hardening to a whitelist, only ~50 safe entries should be readable.
// ============================================================================

describe('Phase 3 — sysctl restrictions', { skip: !IS_MACOS }, () => {

  test('can read whitelisted sysctl (hw.ncpu)', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-sysctl-'));
    try {
      const r = tryRun(cwd, 'sysctl hw.ncpu 2>&1');
      assert.equal(r.status, 0, r.stderr);
      assert.match(r.stdout, /hw\.ncpu:\s*\d+/,
        'Should be able to read hw.ncpu (always in whitelist)');
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });

  test('can read whitelisted sysctl (kern.osversion)', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-sysctl-'));
    try {
      const r = tryRun(cwd, 'sysctl kern.osversion 2>&1');
      assert.equal(r.status, 0, r.stderr);
      assert.match(r.stdout, /kern\.osversion/,
        'Should be able to read kern.osversion (always in whitelist)');
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });

  test('sysctl -a should return a limited set (whitelist only)', () => {
    // With (allow sysctl*), sysctl -a returns 1700+ entries on a typical Mac.
    // After hardening to a whitelist, it should return only ~50-100 entries.
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-sysctl-'));
    try {
      const r = tryRun(cwd, 'sysctl -a 2>/dev/null | wc -l');
      assert.equal(r.status, 0, r.stderr);
      const count = parseInt(r.stdout.trim(), 10);
      assert.ok(count < 200,
        `ESCAPE: sysctl -a returned ${count} entries — (allow sysctl*) is unrestricted.\n` +
        `  Should be <200 after applying whitelist. All kernel tunables are exposed.`
      );
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });
});

// ============================================================================
// Phase 4 — IPC restrictions
//
// (allow ipc*) grants full access to all IPC mechanisms.
// After hardening: only (allow ipc-posix-shm) and (allow ipc-posix-sem).
// ============================================================================

describe('Phase 4 — IPC restrictions', { skip: !IS_MACOS }, () => {

  test('POSIX shared memory should work (needed for common tools)', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-ipc-'));
    try {
      // Python uses POSIX shm for multiprocessing. This should work.
      const r = tryRun(cwd, 'python3 -c "import multiprocessing; print(multiprocessing.cpu_count())" 2>&1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      assert.ok(r.stdout.includes('EXIT:0'),
        `Expected python3 multiprocessing to work, got: ${r.stdout}`);
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });
});

// ============================================================================
// Phase 5 — sandbox_init failure handling
//
// When sandbox_init() fails, boxsh currently prints a warning and continues
// running WITHOUT any sandbox.  This is a critical security flaw — the process
// should refuse to start.
// ============================================================================

describe('Phase 5 — sandbox_init failure handling', { skip: !IS_MACOS }, () => {

  test('basic sandbox is applied successfully', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-sbinit-'));
    try {
      const r = tryRun(cwd, 'echo sandbox-ok');
      assert.equal(r.status, 0, r.stderr);
      assert.equal(r.stdout.trim(), 'sandbox-ok');
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });

  test('sandbox blocks writes to read-only paths', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-sbinit-'));
    try {
      const r = tryRun(cwd, 'touch /usr/test-escape 2>&1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      assert.ok(r.stdout.includes('EXIT:1') || r.stdout.includes('denied') ||
                r.stdout.includes('Permission denied') ||
                r.stdout.includes('Read-only'),
        `Expected write to /usr to be denied, got: ${r.stdout}`);
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });
});

// ============================================================================
// Phase 6 — file-ioctl restrictions
//
// (allow file-ioctl) without scope allows ioctl on any device file.
// After hardening: restricted to specific device paths (/dev/null, /dev/tty, etc.)
// ============================================================================

describe('Phase 6 — file-ioctl / device restrictions', { skip: !IS_MACOS }, () => {

  test('/dev/null is accessible', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-ioctl-'));
    try {
      const r = tryRun(cwd, 'echo test > /dev/null 2>&1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      assert.ok(r.stdout.includes('EXIT:0'),
        `Expected /dev/null operations to work, got: ${r.stdout}`);
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });

  test('/dev/urandom is accessible for reading', () => {
    const cwd = fs.mkdtempSync(path.join(TEMPDIR, 'boxsh-ioctl-'));
    try {
      const r = tryRun(cwd, 'dd if=/dev/urandom bs=16 count=1 2>/dev/null | od -x | head -1; echo EXIT:$?');
      assert.equal(r.status, 0, r.stderr);
      assert.ok(r.stdout.includes('EXIT:0'),
        `Expected /dev/urandom read to work, got: ${r.stdout}`);
    } finally {
      spawnSync('rm', ['-rf', cwd]);
    }
  });
});
